# Generated by Django 5.2.1 on 2025-05-28 18:57

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_created_183a3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_user_id_1547df_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for your post', null=True, upload_to=posts.models.post_image_path),
        ),
    ]
