# Generated by Django 5.2.1 on 2025-05-27 22:30

import userProfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to=userProfile.models.profile_image_path),
        ),
    ]
